### ISSUE TITLE
Error input does not seem to apply

### ISSUE THREAD

**Issue by chrismcleod** [serverless-components/tencent-website#16]
I have this serverless.yml

```yaml
component: tencent-website
name: ***
stage: dev

inputs:
  src:
    root: ./
    src: ./build
    index: index.html
    error: index.html
    websitePath: ./
  region: ...
  bucketName: ...
  protocol: http
```

Expected:
After deploying, the bucket configuration would have the error document set to index.html

Actual:
After deploying, the bucket configuration had the error document set to error.html
