### ISSUE TITLE
请求中的SecretId没有被主账户授权访问本接口

### ISSUE THREAD

**Issue by iqingting** [serverless-components/tencent-website#19]
`serverless.yml` 配置了 `hosts` 属性后发布时报错「请求中的SecretId没有被主账户授权访问本接口」，去掉 `hosts` 配置可以正常 work

``` bash
$ sls --debug

Initializing...
Action: "deploy" - Stage: "dev" - App: "org-app" - Instance: "org-frontend"
Deploying...
the code will be uploaded to https://sp-ins-prod-1300963013.cos.ap-guangzhou.myqcloud.com/bdc64de5-1d04-4b54-91ff-c14ca844f3a0.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1589450136;1589450736&q-key-time=1589450136;1589450736&q-header-list=&q-url-param-list=&q-signature=xxxx

 undefined

5s › org-frontend › 请求中的SecretId没有被主账户授权访问本接口。
```

yaml 配置如下：

``` yml
org: org
app: org-app
component: website
name: org-frontend

inputs:
  src:
    src: ./public
    index: index.html
    error: index.html
  region: ${env:REGION}
  bucketName: org-frontend
  protocol: https
  hosts:
    - host: www.xxx.xyz
      https:
        certId: xxx
        http2: on
        httpsType: 4
        forceSwitch: -2
```

.env

```
# global config
REGION=ap-shanghai
ZONE=ap-shanghai-2
```

**Comment by Jiachen0417** [comment]
您好，请问这个报错目前解决了吗？如果没有的话我们这边排查一下具体的问题

**Comment by iqingting** [comment]
没有，现在的报错是 `The provided credentials could not be validated. Please check your signature is correct.`

看起来还是同样的问题

**Comment by yugasun** [comment]
@iqingting 这里配置 `hosts` 是给 COS 配置 CDN 加速域名，可以去控制台确认下是否开启 CDN 服务？

**Comment by iqingting** [comment]
已经开启了，并且域名也做了 CNAME 配置

**Comment by tinafangkunding** [comment]
@iqingting 您方便贴一下 yaml 的配置吗？刚才测试了一下可以开启自定义域名
```yaml
  protocol: https
  hosts:
    - host: v2ex.tinafang.com
      async: true
      autoRefresh: true
```
```
cdnDomains: 
  - 
    domain:      http://v2ex.tinafang.com
    cname:       v2ex.tinafang.com.cdn.dnsv1.com
    refreshUrls: 
      - http://v2ex.tinafang.com
      - https://v2ex.tinafang.com

Full details: https://serverless.cloud.tencent.com/instances/websiteApp%3Adev%3Awebsitedemo

6s › websitedemo › Success
```

**Comment by tinafangkunding** [comment]
我好像复现了，在您提供的 yaml 里面 certid 参数在 v2 版本需要这样配置
```
      https:
        switch: on
        http2: on
        certInfo:
          certId: 'abc'
```
我这样配置后出现了相同问题
```
4s › websitedemo › Error: The provided credentials could not be validated. Please check your signature is correct.
```

**Comment by iqingting** [comment]
对，看起来是 https 配置的问题，然后我现在的报错是 `域名存在特殊配置`

**Comment by tinafangkunding** [comment]
收到，正在定位了

**Comment by tinafangkunding** [comment]
``` 
     https:
        switch: on # 强制 https
        certInfo:
          certId: 'xxx'
```
辛苦增加一下这个参数试试呢？我刚才增加了该参数后就可以部署成功。研发同学也同步在修改这块的逻辑

**Comment by yugasun** [comment]
@iqingting 这里先配置 `switch` 为 `on`，后面会优化为如果配置了 `https` 默认强制  `https`。

**Comment by iqingting** [comment]
加了的，现在的配置是这样
```
  protocol: https
  hosts:
    - host: www.xxx.xyz
      https:
        switch: on
        certInfo:
          certId: xxx
```

报错是 `域名存在特殊配置`
