### ISSUE TITLE
refreshCdn 部分的参数没有详细说明

### ISSUE THREAD

**Issue by egcn** [serverless-components/tencent-website#27]
我想刷新目录里的全部资源，而 [refreshcdn](https://github.com/serverless-components/tencent-website/blob/v2/docs/configure.md#refreshcdn) 没有说明这部分内容，因此不清楚以下方法是否奏效：
```
      refreshCdn:
        Action: PurgePathCache
        FlushType: flush
        urls: '["https://www.example.com/"]'
```
