### ISSUE TITLE
 基于NextJS的静态式部署，有两个问题 🤔

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-website#36]
1. 每次部署完后，都需要打开浏览器，跑到bucket管理页面中里手动设置 忽略html扩展名选项，不然直接手动访问导出到页面会返回bucket默认到404错误页面：
![image](https://user-images.githubusercontent.com/12392903/112512320-3a8c8880-8dce-11eb-851f-6099f0166ba3.png)

~~2. 我使用NextJS开发的前端工程，使用框架自带到`yarn build && next export` 作为serverless配置文件里到到hook 配置，但是发现没有按照预期实现env.js正常生成与注入到window变量中。~~    ->已自行解决 😄

希望官方到大佬关注一下萌新，我愿意协助一起调查这个问题，帮助大家更好到使用腾讯云到serverless :D

**Comment by yugasun** [comment]
@BetterLuke 感谢反馈，这里我们做下调研先

**Comment by yugasun** [comment]
@BetterLuke 如果要忽略 html 后缀，只需要 `serverless.yml`  中新增 `ignoreHtmlExt` 配置，如下：

```yaml
app: appDemo
stage: dev
component: website
name: websiteDemo

inputs:
  src:
    src: ./src
    index: index.html
    error: index.html
  region: ap-guangzhou
  ignoreHtmlExt: true  # 指定忽略 html 后缀
  bucketName: my-bucket
  protocol: https

```
