### ISSUE TITLE
使用GitHub Action部署时 配置的SECRET无效

### ISSUE THREAD

**Issue by Akitata** [serverless-components/tencent-website#42]
在项目中配置了.env中`TENCENT_SECRET_ID`与`TENCENT_SECRET_KEY`，在本地`sls deploy`操作可正常执行。

在GitHub Action中，使用`sls deploy`报错，提示：

```
> Run sls info

serverless ⚡components

This is a Serverless Framework Component, a premium development experience. Run "serverless login" to use it for free with these features:

  • Instant Deployments
  • Real-Time Logs In Your CLI
  • State Storage, Secrets Management
  • And More: https://github.com/serverless/components

Note - This is an optional SaaS feature, where our hosted cloud engine can access your credentials and code alike a CI/CD product. Learn more here: https://github.com/serverless/components#security-considerations

Serverless › Please log in by running "serverless login" 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 


25h
Error: Process completed with exit code 1.
```

如果前置step中加入: `run sls login`，则无限循环提示：

```
Serverless › Awaiting successful login in your browser 
aNA
Serverless › Awaiting successful login in your browser 
```

完整的github action配置如下：
```
name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g serverless
    - run: cat .env
    - run: sls login
    - run: sls deploy
```

serverless.yml配置如下：
```
component: website
name: website
app: test
org: 'test'
stage: dev

inputs:
  src:
    src: ./src
    index: index.html
    error: index.html
  region: ap-shanghai
  bucketName: test
  protocol: https
  isAutoCiDeploy: false
  cors:
    - allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
      allowedHeaders: '*'
      maxAgeSeconds: 0
  replace: false
```
